version: 2

sources:
  - name: crm_raw_contract_marts
    schema: crm_analytics
    tables:
      - name: staging_crm_contacts
        description: "Cleaned CRM contacts loaded from CSV"
        columns:
          - name: contact_id
            description: "Unique contact identifier"
          - name: email
            description: "Email of the contact"
          - name: created_at
            description: "Timestamp when contact was created"
          - name: country
            description: "Country of the contact"
          - name: phone
            description: "Phone number of the contact"
          - name: email_opt_in
            description: "Whether the contact has opted in for email"
