name: dbt-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-build-and-test:
    runs-on: ubuntu-latest
    container:
      image: barahow/airflow:latest
      options: --user root
    env:
      DBT_PROFILES_DIR: ./dbt/etl_models/dbt_env
      GOOGLE_APPLICATION_CREDENTIALS: ./airflow/secrets/ga4_meta_crm.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up service account
        run: |
          mkdir -p airflow/secrets
          echo "${{ secrets.GA4_META_CRM_JSON }}" > airflow/secrets/ga4_meta_crm.json
        shell: bash

      - name: Verify dbt files
        run: |
          echo "Listing files in dbt/etl_models"
          ls -la dbt/etl_models
          test -f dbt/etl_models/dbt_project.yml

      - name: Install dbt and SQLFluff
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery sqlfluff sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps --project-dir dbt/etl_models

      - name: Lint SQL with SQLFluff
        run: python -m sqlfluff lint dbt/etl_models/models/ --dialect bigquery

      - name: Compile dbt project
        run: dbt compile --project-dir dbt/etl_models --profiles-dir ./dbt/etl_models/dbt_env

      - name: Run dbt build
        run: dbt build --project-dir dbt/etl_models --profiles-dir ./dbt/etl_models/dbt_env --fail-fast --select state:modified+

      - name: Run dbt tests
        run: dbt test --project-dir dbt/etl_models --profiles-dir ./dbt/etl_models/dbt_env --select tag:critical
